# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'testlib',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:junit',
    '3rdparty:mongodb-drivers',
    '3rdparty:netty4',
    '3rdparty:reactive-streams',
    'src/jvm/io/fsq/rogue/connection',
  ],
)
