# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

spindle_thrift_library(
  name = 'thriftexample',
  dependencies = [
    '3rdparty:bson',
    'src/jvm/io/fsq/spindle/runtime',
    'test/thrift/io/fsq/thriftexample/av',
  ],
  sources = globs('*.thrift'),
)
