# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'macros',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:scala-reflect',
  ],
  tags = [
    'fscommon',
  ],
)
