junit_tests(
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:jts',
    '3rdparty:specs2',
    'src/jvm/io/fsq/geo/quadtree',
    'test/jvm/io/fsq/specs2',
  ],
  tags = [
    'opensource',
    'dependencies_must_have:opensource',
  ],
)
