python_library(
  name = 'tracing',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:jaeger-client',
    '3rdparty/python:opentracing',
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:py-zipkin',
    '3rdparty/python:requests',
  ],
)
