# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'types',
  sources = globs('*.scala'),
  provides=scala_artifact(
    org='io.fsq',
    name='rogue-types',
    repo=oss_sonatype_repo,
  ),
)
