scala_library(
  name = 'common',
  sources = globs('*.scala'),
  provides=scala_artifact(
    org='io.fsq',
    name='hfile-common',
    repo=oss_sonatype_repo,
    publication_metadata=io_fsq_library("""
      Foursquare's Hfile common library.
    """),
  ),
)
