# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'callback',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:mongodb-drivers',
    'src/jvm/io/fsq/common/scala',
  ],
)
