
python_library(
  name = 'core',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:ansicolors',
    '3rdparty/python:pantsbuild.pants',
    'src/python/fsqio/pants/buildgen/core/subsystems',
  ],
)
