# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'targets',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:pantsbuild.pants.contrib.node',
  ],
)
