# Copyright 2022 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'testlib',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:junit',
    '3rdparty:mongodb-drivers',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/adapter',
    'src/jvm/io/fsq/rogue/connection',
    'src/jvm/io/fsq/rogue/query',
    'src/jvm/io/fsq/rogue/util',
    'src/jvm/io/fsq/spindle/rogue/adapter',
    'src/jvm/io/fsq/spindle/rogue/query',
    'src/jvm/io/fsq/spindle/runtime',
    'test/jvm/io/fsq/rogue/connection/testlib',
  ],
)
