# Copyright 2020 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  dependencies = [
    '3rdparty:junit',
    '3rdparty:lift-json',
    '3rdparty:scalacheck',
    'src/jvm/io/fsq/common/scala',
    'src/jvm/io/fsq/json/lift',
  ],
)
