# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

python_tests(
  name = 'influx',
  sources = globs("*.py"),
  dependencies = [
    '3rdparty/python:mock',
    '3rdparty/python:pytz',
    '3rdparty/python:requests',
    '3rdparty/python:unittest2',
    'src/python/fsqio/util',
  ],
)
