#!/bin/bash
# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

# Pass variables to children
set -ea

# BUILD_ROOT is treated as a top-level constant if used as part of a Pants invocation.
readonly BUILD_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BUILD_ROOT

# If the PANTS_CONFIG_OVERRIDE is set, stash for use below.
if [ -n "$PANTS_CONFIG_OVERRIDE" ]; then
  PANTS_INI="$PANTS_CONFIG_OVERRIDE"
fi

if [[ -z "$SKIP_UPKEEP" ]]; then
  ./upkeep
fi

# Copied to root by upkeep.
if [[ -e "${BUILD_ROOT}/environ.sh" ]]; then
  source "${BUILD_ROOT}/environ.sh"
else
  echo "Caution: No environ.sh file was found so some common environmental variables may not be defined!"
fi

# If the PANTS_INI was set above, then override the default PANTS_CONFIG_OVERRIDE in environ.sh.
if [ -n "$PANTS_INI" ]; then
  export PANTS_CONFIG_OVERRIDE="$PANTS_INI"
fi


if [ -z "$PANTSBINARY" ]; then
  exec .pvenvs/fs/bin/pants "$@"
else
  export PYTHONPATH=src/python
  exec "$PANTSBINARY" "$@"
fi
