#!/bin/bash
# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

# Pass variables to children
set -ea

# TODO: The empty quotes are to avoid passing args to upkeep, need a better way to handle this.
source upkeep ''
source "${ENV_FILE_LOCATION}"

# We could just execute upkeep if we were okay with pants magically knowing to source 'environ.sh' path.
"${BUILD_ROOT}/upkeep"
if [ -z "$PANTSBINARY" ]; then
  exec .pvenvs/fs/bin/pants "$@"
else
  export PYTHONPATH=src/python
  exec "$PANTSBINARY" "$@"
fi
