#!/bin/bash
# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

# Pass variables to children
set -eoa pipefail
set +a
# BUILD_ROOT is treated as a top-level constant and should always be derived from here.
readonly BUILD_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BUILD_ROOT
export UPKEEPROOT="${BUILD_ROOT}/scripts/fsqio/upkeep"
export DEPENDENCIES_ROOT="${BUILD_ROOT}/dependencies"

ENV_FILE_LOCATION="${BUILD_ROOT}/environ.sh"

# Symlink the proper environmental variables script to the buildroot, using 'scripts/foursquare' to check if in Fsq.io.
if [[ -e "scripts/foursquare" ]]; then
  repo_env='scripts/foursquare/upkeep/libs/env.sh'
else
  repo_env="${UPKEEPROOT}/libs/env.sh"
fi
ln -sf "${repo_env}" "${ENV_FILE_LOCATION}"

source "${ENV_FILE_LOCATION}"
source "${UPKEEPROOT}/util.sh"

# TODO: namespaces=( $(ls -d scripts/*/upkeep) )

function upkeep_cmd() {
  if [ -z "$SKIP_UPKEEP" ]; then
    if [ ! -f "${1}" ]; then
      exit_with_failure "No upkeep file found at: ${1}"
    fi
    echo "${1}"
  fi
}

# TODO(mateo): add an option to list downstream tasks.
case "$1" in
  "help"|"--help"|"-h" )
    print_help
    exit
    ;;
  "force"|"check" )
    action="${UPKEEPROOT}/${1}.sh"
    args=( "${@:2}" )
    ;;
  '')
    action="${UPKEEPROOT}/check.sh"
    args=()
    ;;
  "tasks" )
    print_all_tasks
    exit
    ;;
  "task-list" )
    all_task_names
    exit
    ;;
  "run" )
    # The script can be ${script_name}.sh under <xyz>/upkeep/scripts or be a full file path relative to the BUILD_ROOT.
    action=$(find_script "${@:2}")
    args=( "${@:3}" )

    # Execute `./upkeep check' in order to run any required tasks. SKIP_UPKEEP is respected transitively.
    $(upkeep_cmd ${UPKEEPROOT}/check.sh)
    ;;
  *)
    action="${UPKEEPROOT}/run.sh"
    args=( "${@:1}" )
    ;;
esac

if [ "$0" = "$BASH_SOURCE" ]; then
  cmd=$(upkeep_cmd "${action}")
  exec ${cmd} "${args[@]}"
fi
