# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'fsqio',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:pex',
    '3rdparty/python:six',
    '3rdparty/python:twitter.common.collections',
    'src/python/fsqio/pants/spindle/targets',
  ],
 )