# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'batch',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:casbah',
    '3rdparty:salat',
    'src/jvm/io/fsq/twofishes/indexer/importers/geonames',
    'src/jvm/io/fsq/twofishes/indexer/mongo',
    'src/jvm/io/fsq/twofishes/util',
    'src/thrift/io/fsq/twofishes',
  ],
)
