# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'resolvers',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants.contrib.node',
    'src/python/fsqio/pants/node/targets',
  ],
)
