# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'util',
  sources = globs('*.scala'),
  tags = [
    'fscommon'
  ],
  dependencies = [
    '3rdparty:concurrentlinkedhashmap',
    '3rdparty:joda-time',
    '3rdparty:mail',
    '3rdparty:ostrich',
    '3rdparty:twitter-util',
    '3rdparty:typesafe-config',
    'src/resources/io/fsq/exceptionator/config',
  ],
)
