# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'algorithm',
  sources = globs('*.scala'),
  tags = [
    'fscommon'
  ],
  dependencies = [
    'src/jvm/io/fsq/common/scala',
  ],
)

