# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

# TODO(mateo): Define some useful metadata.
scala_library(
  name = 'algorithm',
  sources = globs('*.scala'),
  tags = [
    'fscommon'
  ],
  dependencies = [
    'src/jvm/io/fsq/common/scala',
  ],
  provides = scala_artifact(
    org = 'io.fsq',
    name = 'common-algorithm',
    repo = oss_sonatype_repo,
  ),
)

