# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'fhttp',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:commons-httpclient',
    '3rdparty:commons-logging',  # Runtime dep.
    '3rdparty:finagle',
    '3rdparty:netty',
    '3rdparty:scala-xml',
    '3rdparty:twitter-util',
  ],
)
