# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'output',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:hadoop-common',
    '3rdparty:jts',
    'src/jvm/io/fsq/twofishes/core',
    'src/jvm/io/fsq/twofishes/indexer/output',
    'src/jvm/io/fsq/twofishes/indexer/util',
    'src/jvm/io/fsq/twofishes/util',
    'src/thrift/io/fsq/twofishes',
  ],
)
