# Copyright 2020 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'json',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:joda-time',
    '3rdparty:lift-json',
    '3rdparty:thrift',
    'src/jvm/io/fsq/json/lift',
    'src/jvm/io/fsq/spindle/common/thrift/json',
  ],
)
