# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'io',
  sources = globs('*.scala'),
  tags = [
    'fscommon'
  ],
  dependencies = [
    '3rdparty:lift-json',
    'src/jvm/io/fsq/exceptionator/util',
  ],
)
