# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'node',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    'src/python/fsqio/pants/node/subsystems',
    'src/python/fsqio/pants/node/subsystems/resolvers',
    'src/python/fsqio/pants/node/targets',
    'src/python/fsqio/pants/node/tasks',
  ],
)
