python_tests(
  name = 'jvm',
  sources = globs("*.py"),
  dependencies = [
    '//:pants',
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:pantsbuild.pants.testinfra',
    'src/python/fsqio/pants/buildgen/jvm/core',
  ],
)
