# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

jvm_binary(
  name = 'exceptionator',
  main = 'io.fsq.exceptionator.service.ExceptionatorServer',
  dependencies = [
    'src/jvm/io/fsq/exceptionator/service',
  ],
)
