# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'util',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pytz',
    '3rdparty/python:requests',
    '3rdparty/python:six',
  ],
)
