# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'adapter',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:bson',
    '3rdparty:mongodb-drivers',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/adapter/callback',
    'src/jvm/io/fsq/rogue/index',
  ],
)
