# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'output',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:casbah',
    '3rdparty:hadoop-common',
    '3rdparty:hbase',
    '3rdparty:jts',
    '3rdparty:mongodb',
    '3rdparty:salat',
    '3rdparty:thrift',
    '3rdparty:twitter-util',
    'src/jvm/io/fsq/common/scala',
    'src/jvm/io/fsq/twofishes/core',
    'src/jvm/io/fsq/twofishes/hacks',
    'src/jvm/io/fsq/twofishes/indexer/mongo',
    'src/jvm/io/fsq/twofishes/indexer/util',
    'src/jvm/io/fsq/twofishes/util',
    'src/thrift/io/fsq/twofishes',
  ],
)
