# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'field',
  sources = globs('*.scala'),
  tags = [
    'fscommon',
    'spindle_codegen',
  ],
  provides=scala_artifact(
    org='io.fsq',
    name='field',
    repo=oss_sonatype_repo,
    publication_metadata=io_fsq_library("""
      Foursquare's Rogue-Field is a set of interfaces for defining the fields of models.
    """),
  ),
)
