# Copyright 2020 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  dependencies = [
    '3rdparty:junit',
    '3rdparty:mockito',
    '3rdparty:ostrich',
    'src/jvm/io/fsq/net/stats',
  ],
  sources = globs('*.scala'),
)
