python_library(
  name = 'tasks',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:future',
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:pex',
    '3rdparty/python:setuptools',
    '3rdparty/python:six',
    '3rdparty/python:typing',
  ],
)
