# Copyright 2015 Foursquare Labs, Inc. All Rights Reserved.

python_library(
  name = 'scripts',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:psycopg2',
    '3rdparty/python:pymongo',
  ],
)
