
python_library(
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    'src/python/fsqio/pants/buildgen/core',
    'src/python/fsqio/pants/buildgen/core/subsystems',
    'src/resources/io/fsq/buildgen',
  ],
  tags = [
    'opensource',
    'buildgen',
    'dependencies_must_have:opensource',
    'dependencies_must_have:buildgen',
  ],
)
