
python_library(
  name = 'scala',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    'src/python/fsqio/pants/buildgen/core',
    'src/python/fsqio/pants/buildgen/jvm',
  ],
)
