# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'index',
  sources = globs('*.scala'),
  dependencies = [
    'src/jvm/io/fsq/field',
    'src/jvm/io/fsq/spindle/runtime',
  ],
)
