# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'index',
  sources = globs('*.scala'),
  dependencies = [
    'src/jvm/io/fsq/field',
  ],
  provides=scala_artifact(
    org='io.fsq',
    name='rogue-index',
    repo=oss_sonatype_repo,
  ),
)
