# Copyright 2020 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:jackson-scala',
    '3rdparty:junit',
    '3rdparty:scalatest',
    '3rdparty:twitter-util',
    'src/jvm/io/fsq/twitter/ostrich/stats',
  ],
)
