# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:hadoop-common',
    '3rdparty:mongodb',
    '3rdparty:specs2',
    'src/jvm/io/fsq/twofishes/core',
    'src/jvm/io/fsq/twofishes/util',
    'src/thrift/io/fsq/twofishes',
  ],
)
