# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'pom',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:requests',
    '3rdparty/python:requests-futures',
    '3rdparty/python:twitter.common.collections',
  ],
)
