# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'pom_publish',
  sources = ['pom_publish.py', '__init__.py'],
  dependencies = [
    '3rdparty/python:twitter.common.collections',
  ],
  tags = [
    'disable_pylint',
  ],
)
