# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'connection',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:lift-util',
    '3rdparty:mongodb-drivers',
  ],
)
