# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

spindle_thrift_library(
  name = 'av',
  dependencies = [
    'src/jvm/io/fsq/spindle/runtime',
    'test/thrift/io/fsq/spindle/thriftexample/talent',
  ],
  sources = globs('*.thrift'),
)
