# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'tasks',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    'src/python/fsqio/pants/spindle/targets',
  ],
)
