# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:jts',
    'src/jvm/io/fsq/common/scala',
    'src/jvm/io/fsq/twofishes/server',
    'src/jvm/io/fsq/twofishes/util',
    'src/thrift/io/fsq/twofishes',
    'test/jvm/io/fsq/specs2',
  ],
)
