# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'testlib',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:bson',
    '3rdparty:mongodb-drivers',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/adapter',
    'src/jvm/io/fsq/rogue/connection',
    'src/jvm/io/fsq/rogue/index',
    'src/jvm/io/fsq/rogue/query',
  ],
)
