# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'descriptors',
  sources = globs('*.java', '*.scala'),
  dependencies = [
    '3rdparty:thrift',
    'src/jvm/io/fsq/spindle/__shaded_for_spindle_bootstrap__/runtime',
    'src/jvm/io/fsq/spindle/common/thrift/base',
  ],
)

