
/**
 * GENERATED CODE - DO NOT EDIT!
 * Generated by foursquare.thrift.codegen v3.0.0-M15
 *

 */


package io.fsq.spindle.__shaded_for_spindle_bootstrap__.descriptors;

class java_thrift_descriptors {

public static interface JavaSimpleBaseType {
  public abstract int id();
  public int getValue();
}

public static interface JavaRequiredness {
  public abstract int id();
  public int getValue();
}

public static abstract class JavaIncludeMeta<
  IncludeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<IncludeT>,
  IncludeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<IncludeT>,
  IncludeMeta extends JavaIncludeMeta<IncludeT, IncludeRaw, IncludeMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<IncludeT, IncludeMeta> {

}

public static interface JavaInclude<
  IncludeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<IncludeT>,
  IncludeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<IncludeT>,
  IncludeMeta extends JavaIncludeMeta<IncludeT, IncludeRaw, IncludeMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<IncludeT> {

  public String path();
  public scala.Option<String> pathOption();
  public String pathOrNull();
  public String pathOrThrow();
  public boolean pathIsSet();
}

public static interface JavaIncludeMutable<
  IncludeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<IncludeT>,
  IncludeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<IncludeT>,
  IncludeMeta extends JavaIncludeMeta<IncludeT, IncludeRaw, IncludeMeta>
> extends JavaInclude<
    IncludeT, IncludeRaw, IncludeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<IncludeT> {

}

public static abstract class JavaIncludeRaw<
  IncludeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<IncludeT>,
  IncludeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<IncludeT>,
  IncludeMeta extends JavaIncludeMeta<IncludeT, IncludeRaw, IncludeMeta>
> implements JavaIncludeMutable<
    IncludeT, IncludeRaw, IncludeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<IncludeT> {

}
public static abstract class JavaNamespaceMeta<
  NamespaceT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<NamespaceT>,
  NamespaceRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<NamespaceT>,
  NamespaceMeta extends JavaNamespaceMeta<NamespaceT, NamespaceRaw, NamespaceMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<NamespaceT, NamespaceMeta> {

}

public static interface JavaNamespace<
  NamespaceT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<NamespaceT>,
  NamespaceRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<NamespaceT>,
  NamespaceMeta extends JavaNamespaceMeta<NamespaceT, NamespaceRaw, NamespaceMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<NamespaceT> {

  public String language();
  public scala.Option<String> languageOption();
  public String languageOrNull();
  public String languageOrThrow();
  public boolean languageIsSet();

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();
}

public static interface JavaNamespaceMutable<
  NamespaceT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<NamespaceT>,
  NamespaceRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<NamespaceT>,
  NamespaceMeta extends JavaNamespaceMeta<NamespaceT, NamespaceRaw, NamespaceMeta>
> extends JavaNamespace<
    NamespaceT, NamespaceRaw, NamespaceMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<NamespaceT> {

}

public static abstract class JavaNamespaceRaw<
  NamespaceT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<NamespaceT>,
  NamespaceRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<NamespaceT>,
  NamespaceMeta extends JavaNamespaceMeta<NamespaceT, NamespaceRaw, NamespaceMeta>
> implements JavaNamespaceMutable<
    NamespaceT, NamespaceRaw, NamespaceMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<NamespaceT> {

}
public static abstract class JavaAnnotationMeta<
  AnnotationT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<AnnotationT>,
  AnnotationRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<AnnotationT>,
  AnnotationMeta extends JavaAnnotationMeta<AnnotationT, AnnotationRaw, AnnotationMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<AnnotationT, AnnotationMeta> {

}

public static interface JavaAnnotation<
  AnnotationT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<AnnotationT>,
  AnnotationRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<AnnotationT>,
  AnnotationMeta extends JavaAnnotationMeta<AnnotationT, AnnotationRaw, AnnotationMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<AnnotationT> {

  public String key();
  public scala.Option<String> keyOption();
  public String keyOrNull();
  public String keyOrThrow();
  public boolean keyIsSet();

  public String value();
  public scala.Option<String> valueOption();
  public String valueOrNull();
  public String valueOrThrow();
  public boolean valueIsSet();
}

public static interface JavaAnnotationMutable<
  AnnotationT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<AnnotationT>,
  AnnotationRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<AnnotationT>,
  AnnotationMeta extends JavaAnnotationMeta<AnnotationT, AnnotationRaw, AnnotationMeta>
> extends JavaAnnotation<
    AnnotationT, AnnotationRaw, AnnotationMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<AnnotationT> {

}

public static abstract class JavaAnnotationRaw<
  AnnotationT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<AnnotationT>,
  AnnotationRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<AnnotationT>,
  AnnotationMeta extends JavaAnnotationMeta<AnnotationT, AnnotationRaw, AnnotationMeta>
> implements JavaAnnotationMutable<
    AnnotationT, AnnotationRaw, AnnotationMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<AnnotationT> {

}
public static abstract class JavaBaseTypeMeta<
  BaseTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<BaseTypeT>,
  BaseTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<BaseTypeT>,
  BaseTypeMeta extends JavaBaseTypeMeta<BaseTypeT, BaseTypeRaw, BaseTypeMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<BaseTypeT, BaseTypeMeta> {

}

public static interface JavaBaseType<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  BaseTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<BaseTypeT>,
  BaseTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<BaseTypeT>,
  BaseTypeMeta extends JavaBaseTypeMeta<BaseTypeT, BaseTypeRaw, BaseTypeMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<BaseTypeT> {

  public io.fsq.spindle.__shaded_for_spindle_bootstrap__.descriptors.SimpleBaseType simpleBaseType();
  public scala.Option<io.fsq.spindle.__shaded_for_spindle_bootstrap__.descriptors.SimpleBaseType> simpleBaseTypeOption();
  public io.fsq.spindle.__shaded_for_spindle_bootstrap__.descriptors.SimpleBaseType simpleBaseTypeOrNull();
  public io.fsq.spindle.__shaded_for_spindle_bootstrap__.descriptors.SimpleBaseType simpleBaseTypeOrThrow();
  public boolean simpleBaseTypeIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaBaseTypeMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  BaseTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<BaseTypeT>,
  BaseTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<BaseTypeT>,
  BaseTypeMeta extends JavaBaseTypeMeta<BaseTypeT, BaseTypeRaw, BaseTypeMeta>
> extends JavaBaseType<com_twitter_thrift_descriptors_Annotation,
    BaseTypeT, BaseTypeRaw, BaseTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<BaseTypeT> {

}

public static abstract class JavaBaseTypeRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  BaseTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<BaseTypeT>,
  BaseTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<BaseTypeT>,
  BaseTypeMeta extends JavaBaseTypeMeta<BaseTypeT, BaseTypeRaw, BaseTypeMeta>
> implements JavaBaseTypeMutable<com_twitter_thrift_descriptors_Annotation,
    BaseTypeT, BaseTypeRaw, BaseTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<BaseTypeT> {

}
public static abstract class JavaListTypeMeta<
  ListTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ListTypeT>,
  ListTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ListTypeT>,
  ListTypeMeta extends JavaListTypeMeta<ListTypeT, ListTypeRaw, ListTypeMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<ListTypeT, ListTypeMeta> {

}

public static interface JavaListType<
  ListTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ListTypeT>,
  ListTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ListTypeT>,
  ListTypeMeta extends JavaListTypeMeta<ListTypeT, ListTypeRaw, ListTypeMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ListTypeT> {

  public String elementTypeId();
  public scala.Option<String> elementTypeIdOption();
  public String elementTypeIdOrNull();
  public String elementTypeIdOrThrow();
  public boolean elementTypeIdIsSet();
}

public static interface JavaListTypeMutable<
  ListTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ListTypeT>,
  ListTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ListTypeT>,
  ListTypeMeta extends JavaListTypeMeta<ListTypeT, ListTypeRaw, ListTypeMeta>
> extends JavaListType<
    ListTypeT, ListTypeRaw, ListTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ListTypeT> {

}

public static abstract class JavaListTypeRaw<
  ListTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ListTypeT>,
  ListTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ListTypeT>,
  ListTypeMeta extends JavaListTypeMeta<ListTypeT, ListTypeRaw, ListTypeMeta>
> implements JavaListTypeMutable<
    ListTypeT, ListTypeRaw, ListTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ListTypeT> {

}
public static abstract class JavaSetTypeMeta<
  SetTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SetTypeT>,
  SetTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SetTypeT>,
  SetTypeMeta extends JavaSetTypeMeta<SetTypeT, SetTypeRaw, SetTypeMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<SetTypeT, SetTypeMeta> {

}

public static interface JavaSetType<
  SetTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SetTypeT>,
  SetTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SetTypeT>,
  SetTypeMeta extends JavaSetTypeMeta<SetTypeT, SetTypeRaw, SetTypeMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SetTypeT> {

  public String elementTypeId();
  public scala.Option<String> elementTypeIdOption();
  public String elementTypeIdOrNull();
  public String elementTypeIdOrThrow();
  public boolean elementTypeIdIsSet();
}

public static interface JavaSetTypeMutable<
  SetTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SetTypeT>,
  SetTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SetTypeT>,
  SetTypeMeta extends JavaSetTypeMeta<SetTypeT, SetTypeRaw, SetTypeMeta>
> extends JavaSetType<
    SetTypeT, SetTypeRaw, SetTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SetTypeT> {

}

public static abstract class JavaSetTypeRaw<
  SetTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SetTypeT>,
  SetTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SetTypeT>,
  SetTypeMeta extends JavaSetTypeMeta<SetTypeT, SetTypeRaw, SetTypeMeta>
> implements JavaSetTypeMutable<
    SetTypeT, SetTypeRaw, SetTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SetTypeT> {

}
public static abstract class JavaMapTypeMeta<
  MapTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<MapTypeT>,
  MapTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<MapTypeT>,
  MapTypeMeta extends JavaMapTypeMeta<MapTypeT, MapTypeRaw, MapTypeMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<MapTypeT, MapTypeMeta> {

}

public static interface JavaMapType<
  MapTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<MapTypeT>,
  MapTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<MapTypeT>,
  MapTypeMeta extends JavaMapTypeMeta<MapTypeT, MapTypeRaw, MapTypeMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<MapTypeT> {

  public String keyTypeId();
  public scala.Option<String> keyTypeIdOption();
  public String keyTypeIdOrNull();
  public String keyTypeIdOrThrow();
  public boolean keyTypeIdIsSet();

  public String valueTypeId();
  public scala.Option<String> valueTypeIdOption();
  public String valueTypeIdOrNull();
  public String valueTypeIdOrThrow();
  public boolean valueTypeIdIsSet();
}

public static interface JavaMapTypeMutable<
  MapTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<MapTypeT>,
  MapTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<MapTypeT>,
  MapTypeMeta extends JavaMapTypeMeta<MapTypeT, MapTypeRaw, MapTypeMeta>
> extends JavaMapType<
    MapTypeT, MapTypeRaw, MapTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<MapTypeT> {

}

public static abstract class JavaMapTypeRaw<
  MapTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<MapTypeT>,
  MapTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<MapTypeT>,
  MapTypeMeta extends JavaMapTypeMeta<MapTypeT, MapTypeRaw, MapTypeMeta>
> implements JavaMapTypeMutable<
    MapTypeT, MapTypeRaw, MapTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<MapTypeT> {

}
public static abstract class JavaContainerTypeMeta<
  ContainerTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ContainerTypeT>,
  ContainerTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ContainerTypeT>,
  ContainerTypeMeta extends JavaContainerTypeMeta<ContainerTypeT, ContainerTypeRaw, ContainerTypeMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<ContainerTypeT, ContainerTypeMeta> {

}

public static interface JavaContainerType<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_SimpleContainerType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ContainerTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ContainerTypeT>,
  ContainerTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ContainerTypeT>,
  ContainerTypeMeta extends JavaContainerTypeMeta<ContainerTypeT, ContainerTypeRaw, ContainerTypeMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ContainerTypeT> {

  public com_twitter_thrift_descriptors_SimpleContainerType simpleContainerType();
  public scala.Option<com_twitter_thrift_descriptors_SimpleContainerType> simpleContainerTypeOption();
  public com_twitter_thrift_descriptors_SimpleContainerType simpleContainerTypeOrNull();
  public com_twitter_thrift_descriptors_SimpleContainerType simpleContainerTypeOrThrow();
  public boolean simpleContainerTypeIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaContainerTypeMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_SimpleContainerType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ContainerTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ContainerTypeT>,
  ContainerTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ContainerTypeT>,
  ContainerTypeMeta extends JavaContainerTypeMeta<ContainerTypeT, ContainerTypeRaw, ContainerTypeMeta>
> extends JavaContainerType<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_SimpleContainerType,
    ContainerTypeT, ContainerTypeRaw, ContainerTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ContainerTypeT> {

}

public static abstract class JavaContainerTypeRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_SimpleContainerType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ContainerTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ContainerTypeT>,
  ContainerTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ContainerTypeT>,
  ContainerTypeMeta extends JavaContainerTypeMeta<ContainerTypeT, ContainerTypeRaw, ContainerTypeMeta>
> implements JavaContainerTypeMutable<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_SimpleContainerType,
    ContainerTypeT, ContainerTypeRaw, ContainerTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ContainerTypeT> {

}
public static abstract class JavaTyperefMeta<
  TyperefT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TyperefT>,
  TyperefRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TyperefT>,
  TyperefMeta extends JavaTyperefMeta<TyperefT, TyperefRaw, TyperefMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<TyperefT, TyperefMeta> {

}

public static interface JavaTyperef<
  TyperefT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TyperefT>,
  TyperefRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TyperefT>,
  TyperefMeta extends JavaTyperefMeta<TyperefT, TyperefRaw, TyperefMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TyperefT> {

  public String typeAlias();
  public scala.Option<String> typeAliasOption();
  public String typeAliasOrNull();
  public String typeAliasOrThrow();
  public boolean typeAliasIsSet();
}

public static interface JavaTyperefMutable<
  TyperefT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TyperefT>,
  TyperefRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TyperefT>,
  TyperefMeta extends JavaTyperefMeta<TyperefT, TyperefRaw, TyperefMeta>
> extends JavaTyperef<
    TyperefT, TyperefRaw, TyperefMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TyperefT> {

}

public static abstract class JavaTyperefRaw<
  TyperefT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TyperefT>,
  TyperefRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TyperefT>,
  TyperefMeta extends JavaTyperefMeta<TyperefT, TyperefRaw, TyperefMeta>
> implements JavaTyperefMutable<
    TyperefT, TyperefRaw, TyperefMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TyperefT> {

}
public static abstract class JavaTypeMeta<
  TypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeT>,
  TypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeT>,
  TypeMeta extends JavaTypeMeta<TypeT, TypeRaw, TypeMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<TypeT, TypeMeta> {

}

public static interface JavaType<com_twitter_thrift_descriptors_SimpleType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  TypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeT>,
  TypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeT>,
  TypeMeta extends JavaTypeMeta<TypeT, TypeRaw, TypeMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeT> {

  public String id();
  public scala.Option<String> idOption();
  public String idOrNull();
  public String idOrThrow();
  public boolean idIsSet();

  public com_twitter_thrift_descriptors_SimpleType simpleType();
  public scala.Option<com_twitter_thrift_descriptors_SimpleType> simpleTypeOption();
  public com_twitter_thrift_descriptors_SimpleType simpleTypeOrNull();
  public com_twitter_thrift_descriptors_SimpleType simpleTypeOrThrow();
  public boolean simpleTypeIsSet();
}

public static interface JavaTypeMutable<com_twitter_thrift_descriptors_SimpleType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  TypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeT>,
  TypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeT>,
  TypeMeta extends JavaTypeMeta<TypeT, TypeRaw, TypeMeta>
> extends JavaType<com_twitter_thrift_descriptors_SimpleType,
    TypeT, TypeRaw, TypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeT> {

}

public static abstract class JavaTypeRaw<com_twitter_thrift_descriptors_SimpleType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  TypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeT>,
  TypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeT>,
  TypeMeta extends JavaTypeMeta<TypeT, TypeRaw, TypeMeta>
> implements JavaTypeMutable<com_twitter_thrift_descriptors_SimpleType,
    TypeT, TypeRaw, TypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeT> {

}
public static abstract class JavaTypedefMeta<
  TypedefT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypedefT>,
  TypedefRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypedefT>,
  TypedefMeta extends JavaTypedefMeta<TypedefT, TypedefRaw, TypedefMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<TypedefT, TypedefMeta> {

}

public static interface JavaTypedef<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  TypedefT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypedefT>,
  TypedefRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypedefT>,
  TypedefMeta extends JavaTypedefMeta<TypedefT, TypedefRaw, TypedefMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypedefT> {

  public String typeId();
  public scala.Option<String> typeIdOption();
  public String typeIdOrNull();
  public String typeIdOrThrow();
  public boolean typeIdIsSet();

  public String typeAlias();
  public scala.Option<String> typeAliasOption();
  public String typeAliasOrNull();
  public String typeAliasOrThrow();
  public boolean typeAliasIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaTypedefMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  TypedefT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypedefT>,
  TypedefRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypedefT>,
  TypedefMeta extends JavaTypedefMeta<TypedefT, TypedefRaw, TypedefMeta>
> extends JavaTypedef<com_twitter_thrift_descriptors_Annotation,
    TypedefT, TypedefRaw, TypedefMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypedefT> {

}

public static abstract class JavaTypedefRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  TypedefT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypedefT>,
  TypedefRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypedefT>,
  TypedefMeta extends JavaTypedefMeta<TypedefT, TypedefRaw, TypedefMeta>
> implements JavaTypedefMutable<com_twitter_thrift_descriptors_Annotation,
    TypedefT, TypedefRaw, TypedefMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypedefT> {

}
public static abstract class JavaTypeRegistryMeta<
  TypeRegistryT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeRegistryT>,
  TypeRegistryRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeRegistryT>,
  TypeRegistryMeta extends JavaTypeRegistryMeta<TypeRegistryT, TypeRegistryRaw, TypeRegistryMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<TypeRegistryT, TypeRegistryMeta> {

}

public static interface JavaTypeRegistry<com_twitter_thrift_descriptors_Type extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  TypeRegistryT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeRegistryT>,
  TypeRegistryRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeRegistryT>,
  TypeRegistryMeta extends JavaTypeRegistryMeta<TypeRegistryT, TypeRegistryRaw, TypeRegistryMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeRegistryT> {
  public scala.collection.immutable.Map<String, com_twitter_thrift_descriptors_Type> idToType();
  public scala.Option<scala.collection.immutable.Map<String, com_twitter_thrift_descriptors_Type>> idToTypeOption();
  public scala.collection.immutable.Map<String, com_twitter_thrift_descriptors_Type> idToTypeOrDefault();
  public scala.collection.immutable.Map<String, com_twitter_thrift_descriptors_Type> idToTypeOrNull();
  public scala.collection.immutable.Map<String, com_twitter_thrift_descriptors_Type> idToTypeOrThrow();
  public boolean idToTypeIsSet();
  public scala.collection.immutable.Map<String, String> aliasToTypeId();
  public scala.Option<scala.collection.immutable.Map<String, String>> aliasToTypeIdOption();
  public scala.collection.immutable.Map<String, String> aliasToTypeIdOrDefault();
  public scala.collection.immutable.Map<String, String> aliasToTypeIdOrNull();
  public scala.collection.immutable.Map<String, String> aliasToTypeIdOrThrow();
  public boolean aliasToTypeIdIsSet();
}

public static interface JavaTypeRegistryMutable<com_twitter_thrift_descriptors_Type extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  TypeRegistryT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeRegistryT>,
  TypeRegistryRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeRegistryT>,
  TypeRegistryMeta extends JavaTypeRegistryMeta<TypeRegistryT, TypeRegistryRaw, TypeRegistryMeta>
> extends JavaTypeRegistry<com_twitter_thrift_descriptors_Type,
    TypeRegistryT, TypeRegistryRaw, TypeRegistryMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeRegistryT> {

}

public static abstract class JavaTypeRegistryRaw<com_twitter_thrift_descriptors_Type extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  TypeRegistryT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeRegistryT>,
  TypeRegistryRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<TypeRegistryT>,
  TypeRegistryMeta extends JavaTypeRegistryMeta<TypeRegistryT, TypeRegistryRaw, TypeRegistryMeta>
> implements JavaTypeRegistryMutable<com_twitter_thrift_descriptors_Type,
    TypeRegistryT, TypeRegistryRaw, TypeRegistryMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<TypeRegistryT> {

}
public static abstract class JavaConstMeta<
  ConstT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ConstT>,
  ConstRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ConstT>,
  ConstMeta extends JavaConstMeta<ConstT, ConstRaw, ConstMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<ConstT, ConstMeta> {

}

public static interface JavaConst<
  ConstT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ConstT>,
  ConstRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ConstT>,
  ConstMeta extends JavaConstMeta<ConstT, ConstRaw, ConstMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ConstT> {

  public String typeId();
  public scala.Option<String> typeIdOption();
  public String typeIdOrNull();
  public String typeIdOrThrow();
  public boolean typeIdIsSet();

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();

  public String value();
  public scala.Option<String> valueOption();
  public String valueOrNull();
  public String valueOrThrow();
  public boolean valueIsSet();
}

public static interface JavaConstMutable<
  ConstT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ConstT>,
  ConstRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ConstT>,
  ConstMeta extends JavaConstMeta<ConstT, ConstRaw, ConstMeta>
> extends JavaConst<
    ConstT, ConstRaw, ConstMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ConstT> {

}

public static abstract class JavaConstRaw<
  ConstT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ConstT>,
  ConstRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ConstT>,
  ConstMeta extends JavaConstMeta<ConstT, ConstRaw, ConstMeta>
> implements JavaConstMutable<
    ConstT, ConstRaw, ConstMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ConstT> {

}
public static abstract class JavaEnumElementMeta<
  EnumElementT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumElementT>,
  EnumElementRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumElementT>,
  EnumElementMeta extends JavaEnumElementMeta<EnumElementT, EnumElementRaw, EnumElementMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<EnumElementT, EnumElementMeta> {

}

public static interface JavaEnumElement<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  EnumElementT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumElementT>,
  EnumElementRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumElementT>,
  EnumElementMeta extends JavaEnumElementMeta<EnumElementT, EnumElementRaw, EnumElementMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumElementT> {

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();
  public int value();
  public scala.Option<scala.Int> valueOption();
  public int valueOrDefault();
  public java.lang.Integer valueOrNull();
  public int valueOrThrow();
  public boolean valueIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaEnumElementMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  EnumElementT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumElementT>,
  EnumElementRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumElementT>,
  EnumElementMeta extends JavaEnumElementMeta<EnumElementT, EnumElementRaw, EnumElementMeta>
> extends JavaEnumElement<com_twitter_thrift_descriptors_Annotation,
    EnumElementT, EnumElementRaw, EnumElementMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumElementT> {

}

public static abstract class JavaEnumElementRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  EnumElementT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumElementT>,
  EnumElementRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumElementT>,
  EnumElementMeta extends JavaEnumElementMeta<EnumElementT, EnumElementRaw, EnumElementMeta>
> implements JavaEnumElementMutable<com_twitter_thrift_descriptors_Annotation,
    EnumElementT, EnumElementRaw, EnumElementMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumElementT> {

}
public static abstract class JavaEnumMeta<
  EnumT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumT>,
  EnumRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumT>,
  EnumMeta extends JavaEnumMeta<EnumT, EnumRaw, EnumMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<EnumT, EnumMeta> {

}

public static interface JavaEnum<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_EnumElement extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  EnumT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumT>,
  EnumRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumT>,
  EnumMeta extends JavaEnumMeta<EnumT, EnumRaw, EnumMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumT> {

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_EnumElement> elements();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_EnumElement>> elementsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_EnumElement> elementsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_EnumElement> elementsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_EnumElement> elementsOrThrow();
  public boolean elementsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaEnumMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_EnumElement extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  EnumT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumT>,
  EnumRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumT>,
  EnumMeta extends JavaEnumMeta<EnumT, EnumRaw, EnumMeta>
> extends JavaEnum<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_EnumElement,
    EnumT, EnumRaw, EnumMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumT> {

}

public static abstract class JavaEnumRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_EnumElement extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  EnumT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumT>,
  EnumRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<EnumT>,
  EnumMeta extends JavaEnumMeta<EnumT, EnumRaw, EnumMeta>
> implements JavaEnumMutable<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_EnumElement,
    EnumT, EnumRaw, EnumMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<EnumT> {

}
public static abstract class JavaFieldMeta<
  FieldT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FieldT>,
  FieldRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FieldT>,
  FieldMeta extends JavaFieldMeta<FieldT, FieldRaw, FieldMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<FieldT, FieldMeta> {

}

public static interface JavaField<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  FieldT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FieldT>,
  FieldRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FieldT>,
  FieldMeta extends JavaFieldMeta<FieldT, FieldRaw, FieldMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FieldT> {
  public short identifier();
  public scala.Option<scala.Short> identifierOption();
  public short identifierOrDefault();
  public java.lang.Short identifierOrNull();
  public short identifierOrThrow();
  public boolean identifierIsSet();

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();

  public String typeId();
  public scala.Option<String> typeIdOption();
  public String typeIdOrNull();
  public String typeIdOrThrow();
  public boolean typeIdIsSet();
  public scala.Option<io.fsq.spindle.__shaded_for_spindle_bootstrap__.descriptors.Requiredness> requirednessOption();
  public io.fsq.spindle.__shaded_for_spindle_bootstrap__.descriptors.Requiredness requirednessOrNull();
  public io.fsq.spindle.__shaded_for_spindle_bootstrap__.descriptors.Requiredness requirednessOrThrow();
  public boolean requirednessIsSet();
  public scala.Option<String> defaultValueOption();
  public String defaultValueOrNull();
  public String defaultValueOrThrow();
  public boolean defaultValueIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaFieldMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  FieldT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FieldT>,
  FieldRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FieldT>,
  FieldMeta extends JavaFieldMeta<FieldT, FieldRaw, FieldMeta>
> extends JavaField<com_twitter_thrift_descriptors_Annotation,
    FieldT, FieldRaw, FieldMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FieldT> {

}

public static abstract class JavaFieldRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  FieldT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FieldT>,
  FieldRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FieldT>,
  FieldMeta extends JavaFieldMeta<FieldT, FieldRaw, FieldMeta>
> implements JavaFieldMutable<com_twitter_thrift_descriptors_Annotation,
    FieldT, FieldRaw, FieldMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FieldT> {

}
public static abstract class JavaStructMeta<
  StructT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<StructT>,
  StructRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<StructT>,
  StructMeta extends JavaStructMeta<StructT, StructRaw, StructMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<StructT, StructMeta> {

}

public static interface JavaStruct<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  StructT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<StructT>,
  StructRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<StructT>,
  StructMeta extends JavaStructMeta<StructT, StructRaw, StructMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<StructT> {

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> __fields();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Field>> fieldsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> fieldsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> fieldsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> fieldsOrThrow();
  public boolean fieldsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaStructMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  StructT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<StructT>,
  StructRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<StructT>,
  StructMeta extends JavaStructMeta<StructT, StructRaw, StructMeta>
> extends JavaStruct<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Field,
    StructT, StructRaw, StructMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<StructT> {

}

public static abstract class JavaStructRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  StructT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<StructT>,
  StructRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<StructT>,
  StructMeta extends JavaStructMeta<StructT, StructRaw, StructMeta>
> implements JavaStructMutable<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Field,
    StructT, StructRaw, StructMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<StructT> {

}
public static abstract class JavaUnionMeta<
  UnionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<UnionT>,
  UnionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<UnionT>,
  UnionMeta extends JavaUnionMeta<UnionT, UnionRaw, UnionMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<UnionT, UnionMeta> {

}

public static interface JavaUnion<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  UnionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<UnionT>,
  UnionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<UnionT>,
  UnionMeta extends JavaUnionMeta<UnionT, UnionRaw, UnionMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<UnionT> {

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> __fields();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Field>> fieldsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> fieldsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> fieldsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> fieldsOrThrow();
  public boolean fieldsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaUnionMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  UnionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<UnionT>,
  UnionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<UnionT>,
  UnionMeta extends JavaUnionMeta<UnionT, UnionRaw, UnionMeta>
> extends JavaUnion<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Field,
    UnionT, UnionRaw, UnionMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<UnionT> {

}

public static abstract class JavaUnionRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  UnionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<UnionT>,
  UnionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<UnionT>,
  UnionMeta extends JavaUnionMeta<UnionT, UnionRaw, UnionMeta>
> implements JavaUnionMutable<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Field,
    UnionT, UnionRaw, UnionMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<UnionT> {

}
public static abstract class JavaExceptionMeta<
  ExceptionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ExceptionT>,
  ExceptionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ExceptionT>,
  ExceptionMeta extends JavaExceptionMeta<ExceptionT, ExceptionRaw, ExceptionMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<ExceptionT, ExceptionMeta> {

}

public static interface JavaException<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ExceptionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ExceptionT>,
  ExceptionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ExceptionT>,
  ExceptionMeta extends JavaExceptionMeta<ExceptionT, ExceptionRaw, ExceptionMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ExceptionT> {

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> __fields();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Field>> fieldsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> fieldsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> fieldsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> fieldsOrThrow();
  public boolean fieldsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaExceptionMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ExceptionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ExceptionT>,
  ExceptionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ExceptionT>,
  ExceptionMeta extends JavaExceptionMeta<ExceptionT, ExceptionRaw, ExceptionMeta>
> extends JavaException<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Field,
    ExceptionT, ExceptionRaw, ExceptionMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ExceptionT> {

}

public static abstract class JavaExceptionRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ExceptionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ExceptionT>,
  ExceptionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ExceptionT>,
  ExceptionMeta extends JavaExceptionMeta<ExceptionT, ExceptionRaw, ExceptionMeta>
> implements JavaExceptionMutable<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Field,
    ExceptionT, ExceptionRaw, ExceptionMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ExceptionT> {

}
public static abstract class JavaFunctionMeta<
  FunctionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FunctionT>,
  FunctionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FunctionT>,
  FunctionMeta extends JavaFunctionMeta<FunctionT, FunctionRaw, FunctionMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<FunctionT, FunctionMeta> {

}

public static interface JavaFunction<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  FunctionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FunctionT>,
  FunctionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FunctionT>,
  FunctionMeta extends JavaFunctionMeta<FunctionT, FunctionRaw, FunctionMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FunctionT> {

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();
  public scala.Option<String> returnTypeIdOption();
  public String returnTypeIdOrNull();
  public String returnTypeIdOrThrow();
  public boolean returnTypeIdIsSet();
  public boolean oneWay();
  public scala.Option<scala.Boolean> oneWayOption();
  public boolean oneWayOrDefault();
  public java.lang.Boolean oneWayOrNull();
  public boolean oneWayOrThrow();
  public boolean oneWayIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> argz();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Field>> argzOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> argzOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> argzOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> argzOrThrow();
  public boolean argzIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> throwz();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Field>> throwzOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> throwzOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> throwzOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Field> throwzOrThrow();
  public boolean throwzIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaFunctionMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  FunctionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FunctionT>,
  FunctionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FunctionT>,
  FunctionMeta extends JavaFunctionMeta<FunctionT, FunctionRaw, FunctionMeta>
> extends JavaFunction<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Field,
    FunctionT, FunctionRaw, FunctionMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FunctionT> {

}

public static abstract class JavaFunctionRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Field extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  FunctionT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FunctionT>,
  FunctionRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<FunctionT>,
  FunctionMeta extends JavaFunctionMeta<FunctionT, FunctionRaw, FunctionMeta>
> implements JavaFunctionMutable<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Field,
    FunctionT, FunctionRaw, FunctionMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<FunctionT> {

}
public static abstract class JavaServiceMeta<
  ServiceT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ServiceT>,
  ServiceRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ServiceT>,
  ServiceMeta extends JavaServiceMeta<ServiceT, ServiceRaw, ServiceMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<ServiceT, ServiceMeta> {

}

public static interface JavaService<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Function extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ServiceT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ServiceT>,
  ServiceRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ServiceT>,
  ServiceMeta extends JavaServiceMeta<ServiceT, ServiceRaw, ServiceMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ServiceT> {

  public String name();
  public scala.Option<String> nameOption();
  public String nameOrNull();
  public String nameOrThrow();
  public boolean nameIsSet();
  public scala.Option<String> extendzOption();
  public String extendzOrNull();
  public String extendzOrThrow();
  public boolean extendzIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Function> functions();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Function>> functionsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Function> functionsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Function> functionsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Function> functionsOrThrow();
  public boolean functionsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> __annotations();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Annotation>> annotationsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Annotation> annotationsOrThrow();
  public boolean annotationsIsSet();
}

public static interface JavaServiceMutable<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Function extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ServiceT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ServiceT>,
  ServiceRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ServiceT>,
  ServiceMeta extends JavaServiceMeta<ServiceT, ServiceRaw, ServiceMeta>
> extends JavaService<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Function,
    ServiceT, ServiceRaw, ServiceMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ServiceT> {

}

public static abstract class JavaServiceRaw<com_twitter_thrift_descriptors_Annotation extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Function extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ServiceT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ServiceT>,
  ServiceRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ServiceT>,
  ServiceMeta extends JavaServiceMeta<ServiceT, ServiceRaw, ServiceMeta>
> implements JavaServiceMutable<com_twitter_thrift_descriptors_Annotation, com_twitter_thrift_descriptors_Function,
    ServiceT, ServiceRaw, ServiceMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ServiceT> {

}
public static abstract class JavaProgramMeta<
  ProgramT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ProgramT>,
  ProgramRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ProgramT>,
  ProgramMeta extends JavaProgramMeta<ProgramT, ProgramRaw, ProgramMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<ProgramT, ProgramMeta> {

}

public static interface JavaProgram<com_twitter_thrift_descriptors_Const extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Enum extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Exception extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Include extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Namespace extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Service extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Struct extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_TypeRegistry extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Typedef extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Union extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ProgramT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ProgramT>,
  ProgramRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ProgramT>,
  ProgramMeta extends JavaProgramMeta<ProgramT, ProgramRaw, ProgramMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ProgramT> {
  public scala.collection.Seq<com_twitter_thrift_descriptors_Namespace> namespaces();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Namespace>> namespacesOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Namespace> namespacesOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Namespace> namespacesOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Namespace> namespacesOrThrow();
  public boolean namespacesIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Include> includes();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Include>> includesOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Include> includesOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Include> includesOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Include> includesOrThrow();
  public boolean includesIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Const> constants();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Const>> constantsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Const> constantsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Const> constantsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Const> constantsOrThrow();
  public boolean constantsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Enum> enums();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Enum>> enumsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Enum> enumsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Enum> enumsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Enum> enumsOrThrow();
  public boolean enumsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Typedef> typedefs();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Typedef>> typedefsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Typedef> typedefsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Typedef> typedefsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Typedef> typedefsOrThrow();
  public boolean typedefsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Struct> structs();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Struct>> structsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Struct> structsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Struct> structsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Struct> structsOrThrow();
  public boolean structsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Union> unions();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Union>> unionsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Union> unionsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Union> unionsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Union> unionsOrThrow();
  public boolean unionsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Exception> exceptions();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Exception>> exceptionsOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Exception> exceptionsOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Exception> exceptionsOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Exception> exceptionsOrThrow();
  public boolean exceptionsIsSet();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Service> services();
  public scala.Option<scala.collection.Seq<com_twitter_thrift_descriptors_Service>> servicesOption();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Service> servicesOrDefault();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Service> servicesOrNull();
  public scala.collection.Seq<com_twitter_thrift_descriptors_Service> servicesOrThrow();
  public boolean servicesIsSet();

  public com_twitter_thrift_descriptors_TypeRegistry typeRegistry();
  public scala.Option<com_twitter_thrift_descriptors_TypeRegistry> typeRegistryOption();
  public com_twitter_thrift_descriptors_TypeRegistry typeRegistryOrNull();
  public com_twitter_thrift_descriptors_TypeRegistry typeRegistryOrThrow();
  public boolean typeRegistryIsSet();
}

public static interface JavaProgramMutable<com_twitter_thrift_descriptors_Const extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Enum extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Exception extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Include extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Namespace extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Service extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Struct extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_TypeRegistry extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Typedef extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Union extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ProgramT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ProgramT>,
  ProgramRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ProgramT>,
  ProgramMeta extends JavaProgramMeta<ProgramT, ProgramRaw, ProgramMeta>
> extends JavaProgram<com_twitter_thrift_descriptors_Const, com_twitter_thrift_descriptors_Enum, com_twitter_thrift_descriptors_Exception, com_twitter_thrift_descriptors_Include, com_twitter_thrift_descriptors_Namespace, com_twitter_thrift_descriptors_Service, com_twitter_thrift_descriptors_Struct, com_twitter_thrift_descriptors_TypeRegistry, com_twitter_thrift_descriptors_Typedef, com_twitter_thrift_descriptors_Union,
    ProgramT, ProgramRaw, ProgramMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ProgramT> {

}

public static abstract class JavaProgramRaw<com_twitter_thrift_descriptors_Const extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Enum extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Exception extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Include extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Namespace extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Service extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Struct extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_TypeRegistry extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Typedef extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Union extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  ProgramT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ProgramT>,
  ProgramRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<ProgramT>,
  ProgramMeta extends JavaProgramMeta<ProgramT, ProgramRaw, ProgramMeta>
> implements JavaProgramMutable<com_twitter_thrift_descriptors_Const, com_twitter_thrift_descriptors_Enum, com_twitter_thrift_descriptors_Exception, com_twitter_thrift_descriptors_Include, com_twitter_thrift_descriptors_Namespace, com_twitter_thrift_descriptors_Service, com_twitter_thrift_descriptors_Struct, com_twitter_thrift_descriptors_TypeRegistry, com_twitter_thrift_descriptors_Typedef, com_twitter_thrift_descriptors_Union,
    ProgramT, ProgramRaw, ProgramMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<ProgramT> {

}


public static abstract class JavaSimpleContainerTypeMeta<
  SimpleContainerTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleContainerTypeT>,
  SimpleContainerTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleContainerTypeT>,
  SimpleContainerTypeMeta extends JavaSimpleContainerTypeMeta<SimpleContainerTypeT, SimpleContainerTypeRaw, SimpleContainerTypeMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<SimpleContainerTypeT, SimpleContainerTypeMeta> {

}

public static interface JavaSimpleContainerType<com_twitter_thrift_descriptors_ListType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_MapType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_SetType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  SimpleContainerTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleContainerTypeT>,
  SimpleContainerTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleContainerTypeT>,
  SimpleContainerTypeMeta extends JavaSimpleContainerTypeMeta<SimpleContainerTypeT, SimpleContainerTypeRaw, SimpleContainerTypeMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleContainerTypeT> {
  public scala.Option<com_twitter_thrift_descriptors_ListType> listTypeOption();
  public com_twitter_thrift_descriptors_ListType listTypeOrNull();
  public com_twitter_thrift_descriptors_ListType listTypeOrThrow();
  public boolean listTypeIsSet();
  public scala.Option<com_twitter_thrift_descriptors_SetType> setTypeOption();
  public com_twitter_thrift_descriptors_SetType setTypeOrNull();
  public com_twitter_thrift_descriptors_SetType setTypeOrThrow();
  public boolean setTypeIsSet();
  public scala.Option<com_twitter_thrift_descriptors_MapType> mapTypeOption();
  public com_twitter_thrift_descriptors_MapType mapTypeOrNull();
  public com_twitter_thrift_descriptors_MapType mapTypeOrThrow();
  public boolean mapTypeIsSet();
}

public static interface JavaSimpleContainerTypeMutable<com_twitter_thrift_descriptors_ListType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_MapType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_SetType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  SimpleContainerTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleContainerTypeT>,
  SimpleContainerTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleContainerTypeT>,
  SimpleContainerTypeMeta extends JavaSimpleContainerTypeMeta<SimpleContainerTypeT, SimpleContainerTypeRaw, SimpleContainerTypeMeta>
> extends JavaSimpleContainerType<com_twitter_thrift_descriptors_ListType, com_twitter_thrift_descriptors_MapType, com_twitter_thrift_descriptors_SetType,
    SimpleContainerTypeT, SimpleContainerTypeRaw, SimpleContainerTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleContainerTypeT> {

}

public static abstract class JavaSimpleContainerTypeRaw<com_twitter_thrift_descriptors_ListType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_MapType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_SetType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  SimpleContainerTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleContainerTypeT>,
  SimpleContainerTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleContainerTypeT>,
  SimpleContainerTypeMeta extends JavaSimpleContainerTypeMeta<SimpleContainerTypeT, SimpleContainerTypeRaw, SimpleContainerTypeMeta>
> implements JavaSimpleContainerTypeMutable<com_twitter_thrift_descriptors_ListType, com_twitter_thrift_descriptors_MapType, com_twitter_thrift_descriptors_SetType,
    SimpleContainerTypeT, SimpleContainerTypeRaw, SimpleContainerTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleContainerTypeT> {

}

public static abstract class JavaSimpleTypeMeta<
  SimpleTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleTypeT>,
  SimpleTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleTypeT>,
  SimpleTypeMeta extends JavaSimpleTypeMeta<SimpleTypeT, SimpleTypeRaw, SimpleTypeMeta>
> implements io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MetaRecord<SimpleTypeT, SimpleTypeMeta> {

}

public static interface JavaSimpleType<com_twitter_thrift_descriptors_BaseType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_ContainerType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Typeref extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  SimpleTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleTypeT>,
  SimpleTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleTypeT>,
  SimpleTypeMeta extends JavaSimpleTypeMeta<SimpleTypeT, SimpleTypeRaw, SimpleTypeMeta>
> extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleTypeT> {
  public scala.Option<com_twitter_thrift_descriptors_BaseType> baseTypeOption();
  public com_twitter_thrift_descriptors_BaseType baseTypeOrNull();
  public com_twitter_thrift_descriptors_BaseType baseTypeOrThrow();
  public boolean baseTypeIsSet();
  public scala.Option<com_twitter_thrift_descriptors_ContainerType> containerTypeOption();
  public com_twitter_thrift_descriptors_ContainerType containerTypeOrNull();
  public com_twitter_thrift_descriptors_ContainerType containerTypeOrThrow();
  public boolean containerTypeIsSet();
  public scala.Option<com_twitter_thrift_descriptors_Typeref> typerefOption();
  public com_twitter_thrift_descriptors_Typeref typerefOrNull();
  public com_twitter_thrift_descriptors_Typeref typerefOrThrow();
  public boolean typerefIsSet();
}

public static interface JavaSimpleTypeMutable<com_twitter_thrift_descriptors_BaseType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_ContainerType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Typeref extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  SimpleTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleTypeT>,
  SimpleTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleTypeT>,
  SimpleTypeMeta extends JavaSimpleTypeMeta<SimpleTypeT, SimpleTypeRaw, SimpleTypeMeta>
> extends JavaSimpleType<com_twitter_thrift_descriptors_BaseType, com_twitter_thrift_descriptors_ContainerType, com_twitter_thrift_descriptors_Typeref,
    SimpleTypeT, SimpleTypeRaw, SimpleTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleTypeT> {

}

public static abstract class JavaSimpleTypeRaw<com_twitter_thrift_descriptors_BaseType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_ContainerType extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>, com_twitter_thrift_descriptors_Typeref extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<?>,
  SimpleTypeT extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleTypeT>,
  SimpleTypeRaw extends io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.MutableRecord<SimpleTypeT>,
  SimpleTypeMeta extends JavaSimpleTypeMeta<SimpleTypeT, SimpleTypeRaw, SimpleTypeMeta>
> implements JavaSimpleTypeMutable<com_twitter_thrift_descriptors_BaseType, com_twitter_thrift_descriptors_ContainerType, com_twitter_thrift_descriptors_Typeref,
    SimpleTypeT, SimpleTypeRaw, SimpleTypeMeta
  >,
  io.fsq.spindle.__shaded_for_spindle_bootstrap__.runtime.Record<SimpleTypeT> {

}


}
