# Copyright 2022 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'testlib',
  # This package is only for basic test helper utilities. Please
  # try to keep dependencies to a minimum. Do not add any dependencies
  # on Foursquare specific models or services.
  dependencies = [
    '3rdparty:scala-reflect',
  ],
  sources = globs('*.scala'),
)
