# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

ssp_template(
  name = 'scalainterface',
  sources = globs('*.ssp'),
  entry_point = 'record.ssp',
  dependencies = [
    'src/resources/io/fsq/ssp/codegen/javagen',
  ]
)
