# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'test',
  sources = globs('*.scala'),
  tags = [
    'opensource',
  ],
  dependencies = [
    '3rdparty:junit',
    '3rdparty:reflections',
    '3rdparty:scalac',
  ],
)
