# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'testing',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:junit',
    'src/jvm/io/fsq/common/scala',
  ],
  tags = [],
)
