# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:bson',
    '3rdparty:junit',
    '3rdparty:mongodb-drivers',
    '3rdparty:specs2',
    '3rdparty:twitter-util',
    'src/jvm/io/fsq/common/concurrent',
    'src/jvm/io/fsq/common/scala',
    'src/jvm/io/fsq/field',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/adapter',
    'src/jvm/io/fsq/rogue/adapter/twitter',
    'src/jvm/io/fsq/rogue/connection',
    'src/jvm/io/fsq/rogue/index',
    'src/jvm/io/fsq/rogue/query',
    'src/jvm/io/fsq/rogue/util',
    'test/jvm/io/fsq/rogue/connection/testlib',
    'test/jvm/io/fsq/rogue/query/testlib',
  ],
)
