

python_library(
  name = 'spindle',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    'src/python/fsqio/pants/spindle/targets',
    'src/python/fsqio/pants/spindle/tasks',
  ],
)

