# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'logging',
  sources = globs('*.scala'),
  tags = [
    'fscommon'
  ],
  dependencies = [
    '3rdparty:twitter-util',
  ],
)

