# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'rogue',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:joda-time',
    '3rdparty:mongodb',
    'src/jvm/io/fsq/field',
    'src/jvm/io/fsq/rogue/index',
  ],
)
