# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_record_library(
  name = 'test',
  sources = globs('*.thrift'),
  dependencies = [
    'src/jvm/io/fsq/spindle/runtime',
    'test/thrift/io/fsq/spindle/rogue/test',
  ],
)
