# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_record_library(
  name = 'model',
  dependencies = [
    '3rdparty:bson',
    'src/jvm/io/fsq/spindle/runtime',
    'src/thrift/io/fsq/twofishes',
  ],
  sources = globs('*.thrift'),
)
