scala_library(
  name = 'mmap',
  dependencies = [
    '3rdparty:hadoop-common',
    '3rdparty:ostrich',
    '3rdparty:snappy-java',
    '3rdparty:twitter-util',
    'src/jvm/io/fsq/common/base',
    'src/jvm/io/fsq/common/logging',
    'src/jvm/io/fsq/common/scala',
    'src/jvm/io/fsq/hfile/reader/service',
  ],
  sources = globs('*.scala')
)
