page(
  name='page',
  source='README.md',
  dependencies=[
    'src/python/fsqio/pants:page',
  ],
  provides=[
    wiki_artifact(wiki=confluence,
      space='ENG',
      title='Buildgen Plugins',
    ),
  ],
)

