
python_library(
  name = 'buildgen',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    'src/python/fsqio/pants/buildgen/core',
    'src/python/fsqio/pants/buildgen/jvm',
    'src/python/fsqio/pants/buildgen/jvm/scala',
    'src/python/fsqio/pants/buildgen/python',
  ],
)
