# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_record_library(
  name = 'testlib',
  sources = globs('*.thrift'),
  dependencies = [
    '3rdparty:bson',
    'src/jvm/io/fsq/spindle/runtime',
    'test/thrift/io/fsq/spindle/rogue/testlib',
  ],
)
