# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'query',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:mongodb-drivers',
    'src/jvm/io/fsq/field',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/adapter',
    'src/jvm/io/fsq/rogue/index',
    'src/jvm/io/fsq/rogue/types',
  ],
)
