# Copyright 2020 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'dollar',
  sources = globs('*.scala'),
  provides = scala_artifact(org='io.fsq.dollar', name='stats', repo=oss_sonatype_repo),
)
