# Copyright 2020 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'dollar',
  sources = globs('*.scala'),
  provides = scala_artifact(
    org = 'io.fsq',
    name = 'dollar-stats',
    repo=oss_sonatype_repo,
    publication_metadata=io_fsq_library("""
      Fsq.io common libraries, from Foursquare.
    """),
  ),
)
