
python_library(
  name = 'source_analysis',
  sources = globs('*.py'),
  tags = [
    'opensource',
    'buildgen',
    'dependencies_must_have:opensource',
    'dependencies_must_have:buildgen',
  ],
)
