# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_record_library(
  name = 'testlib',
  sources = globs('*.thrift'),
  dependencies = [
    '3rdparty:bson',
    '3rdparty:joda-time',
    'src/jvm/io/fsq/spindle/runtime',
  ],
)
