# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'subsystems',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
  ],
  tags = [
    'opensource',
    'buildgen',
    'dependencies_must_have:opensource',
    'dependencies_must_have:buildgen',
  ],
)
