# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

ssp_template(
  name = 'javagen',
  sources = globs('*.ssp'),
  entry_point = 'record.ssp',
  dependencies = [
    'src/resources/io/fsq/ssp/codegen/javagen/field',
  ]
)
