# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:junit',
    'src/jvm/io/fsq/spindle/__shaded_for_spindle_bootstrap__/descriptors',
    'src/jvm/io/fsq/spindle/codegen/parser',
  ],
)
