# Copyright 2012 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'matchers',
  tags = [],
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:hamcrest-core',
    '3rdparty:scala-reflect',
    'src/jvm/io/fsq/common/scala',
  ],
)

