# Copyright 2020 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'stats',
  dependencies = [
    '3rdparty:jackson-scala',
    '3rdparty:twitter-util',
  ],
  sources = globs('*.scala'),
  provides = scala_artifact(org='fsvendor.com.twitter.ostrich', name='stats', repo=internal_artifactory),
)
