# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'scalding',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:cascading',
    '3rdparty:commons-net',
    '3rdparty:country-revgeo',
    '3rdparty:gt-geojson',
    '3rdparty:hadoop-common',
    '3rdparty:icu4j',
    '3rdparty:json4s',
    '3rdparty:jts',
    '3rdparty:rockymadden',
    '3rdparty:scalding',
    'src/jvm/io/fsq/common/scala',
    'src/jvm/io/fsq/twofishes/indexer/importers/geonames',
    'src/jvm/io/fsq/twofishes/indexer/output',
    'src/jvm/io/fsq/twofishes/indexer/util',
    'src/jvm/io/fsq/twofishes/util',
    'src/thrift/io/fsq/twofishes',
  ],
)
