# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:junit',
    '3rdparty:mongodb-drivers',
    'src/jvm/io/fsq/rogue/connection',
    'test/jvm/io/fsq/rogue/connection/testlib',
  ],
)
