page(
  name='page',
  source='README.md',
  links=[
    'src/python/fsqio/pants/buildgen/core',
    'src/python/fsqio/pants/buildgen:page',
  ],
  provides=[
    wiki_artifact(wiki=confluence,
      space='ENG',
      title='Pants Plugins',
    ),
  ],
)
