# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'parser',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:commons-io',
    '3rdparty:parboiled-scala',
    'src/jvm/io/fsq/spindle/__shaded_for_spindle_bootstrap__/descriptors',
  ],
)
