# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'util',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:caliper',
    '3rdparty:gt-shapefile',
    '3rdparty:jts',
    '3rdparty:mongodb',
    '3rdparty:ostrich',
    '3rdparty:s2',
    '3rdparty:slf4s',
    '3rdparty:twitter-util',
    'src/jvm/io/fsq/common/scala',
    'src/jvm/io/fsq/twofishes/util/data',
    'src/thrift/io/fsq/twofishes',
  ],
)
