java_tests(
  name = 'test',
  dependencies = [
    '3rdparty:junit',  # java-buildgen
    '3rdparty:thrift',  # java-buildgen
    'src/jvm/io/fsq/spindle/common/thrift/json',
    'test/thrift/io/fsq/spindle/common/thrift/json/test',  # java-buildgen
  ],
  sources = globs('*.java')
)
