# Copyright 2013 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'base',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:junit',
    '3rdparty:specs',
    'src/jvm/io/fsq/common/base',
  ],
)
