scala_library(
  name = 'base',
  sources = globs('*.scala'),
  provides = scala_artifact(
    org = 'io.fsq',
    name = 'common-base',
    repo = oss_sonatype_repo,
    publication_metadata=io_fsq_library("""
      Fsq.io common libraries, from Foursquare.
    """),
  ),
  tags = [],
)
