# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

spindle_thrift_library(
  name = 'test',
  dependencies = [
    '3rdparty:twitter-util',
    'src/jvm/io/fsq/spindle/runtime',
  ],
  sources = globs('*.thrift'),
)
