# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'fsqio',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:ansicolors',
    '3rdparty/python:future',
  ],
)
