# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

ssp_template(
  name = 'scala',
  sources = globs('*.ssp'),
  entry_point = 'record.ssp',
  dependencies = [
    'src/resources/io/fsq/ssp/codegen/scala/compare',
    'src/resources/io/fsq/ssp/codegen/scala/field',
    'src/resources/io/fsq/ssp/codegen/scala/read',
    'src/resources/io/fsq/ssp/codegen/scala/write',
    'src/resources/io/fsq/ssp/codegen/javagen',
  ]
)
