# Copyright 2018 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'concrete',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:mongodb-drivers',
    'src/jvm/io/fsq/exceptionator/mongo',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/adapter',
    'src/jvm/io/fsq/rogue/connection',
    'src/jvm/io/fsq/rogue/query',
    'src/jvm/io/fsq/rogue/util',
    'src/jvm/io/fsq/spindle/rogue/adapter',
    'src/jvm/io/fsq/spindle/rogue/query',
  ],
  tags = [
    'fscommon',
    'opensource',
    'dependencies_must_have:opensource',
  ],
)
