# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'annotations',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:json4s',
    '3rdparty:reflections',
  ],
  tags = [
    'opensource',
    'dependencies_must_have:opensource',
  ],
)
