# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'salatfork',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:casbah',
    '3rdparty:mongodb-drivers',
    '3rdparty:salat',
  ],
)
