
python_library(
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:pantsbuild.pants.contrib.confluence',
    'src/python/fsqio/pants/wiki/subsystems',
    'src/python/fsqio/pants/wiki/util',
  ],
)
