python_library(
  name = 'tasks',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:setuptools',
    '3rdparty/python:six',
    'src/python/fsqio/pants/rpmbuild/subsystems',
    'src/python/fsqio/pants/rpmbuild/targets',
  ],
)
