buildgen_target_bag(
  name = 'all_thrift',
  target_type_alias = 'scala_record_library',
  source_tree = 'src/thrift',
  dependencies = [
    'src/thrift/io/fsq/twofishes',
  ],
  tags = [
    'opensource'
  ],
)
