buildgen_target_bag(
  name = 'all_thrift',
  target_type_alias = 'scala_record_library',
  source_tree = 'src/thrift/io/fsq',
  dependencies = [
    'src/thrift/io/fsq/common/thrift/descriptors/constants/gen',
    'src/thrift/io/fsq/common/thrift/descriptors/enums/gen',
    'src/thrift/io/fsq/common/thrift/descriptors/headers/gen',
    'src/thrift/io/fsq/common/thrift/descriptors/programs/gen',
    'src/thrift/io/fsq/common/thrift/descriptors/services/gen',
    'src/thrift/io/fsq/common/thrift/descriptors/structs/gen',
    'src/thrift/io/fsq/common/thrift/descriptors/types/gen',
    'src/thrift/io/fsq/twofishes',
    'src/thrift/io/fsq/twofishes/model',
  ],
  tags = [
    'opensource'
  ],
)
