# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:hamcrest-core',
    '3rdparty:junit',
    'test/jvm/io/fsq/common/testing',
    'test/jvm/io/fsq/common/testing/matchers',
  ],
)
