# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'model',
  sources = globs('*.scala'),
  tags = [
    'fscommon'
  ],
  dependencies = [
    '3rdparty:joda-time',
    '3rdparty:lift-common',
    '3rdparty:lift-json',
    '3rdparty:lift-mongo',
    '3rdparty:lift-record',
    '3rdparty:mongodb',
    'src/jvm/io/fsq/exceptionator/model/io',
    'src/jvm/io/fsq/exceptionator/util',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/index',
    'src/jvm/io/fsq/rogue/indexchecker',
    'src/jvm/io/fsq/rogue/lift',
    'src/jvm/io/fsq/rogue/spindle',
  ],
)
