# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:joda-time',
    '3rdparty:junit',
    '3rdparty:lift-mongo',
    '3rdparty:lift-record',
    '3rdparty:lift-util',
    '3rdparty:mongodb',
    '3rdparty:specs2',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/index',
    'src/jvm/io/fsq/rogue/indexchecker',
    'src/jvm/io/fsq/rogue/lift',
    'test/jvm/io/fsq/rogue/test',
    'test/jvm/io/fsq/util/compiler/test',
  ],
)
