# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'scala',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:junit',
    '3rdparty:scalacheck',
    '3rdparty:specs',
    'src/jvm/io/fsq/common/scala',
  ],
)
