# Copyright 2017 Foursquare Labs Inc. All Rights Reserved.

python_library(
  name = 'fsqio',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
  ],
 )

# Source code is inlined by a README.md file.
resources(
  name = 'publish-register',
  sources = globs('register.py'),
)
