# Copyright 2016 Foursquare Labs Inc. All Rights Reserved.

# TODO(mateo): Move the templates to a long-term location and manage them with a BUILD file.

python_library(
  name = 'publish',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:pantsbuild.pants',
    '3rdparty/python:twitter.common.collections',
  ],
)
