# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'mongo',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:bson',
    '3rdparty:casbah',
    '3rdparty:mongodb-drivers',
    '3rdparty:salat',
    'src/jvm/io/fsq/twofishes/indexer/util',
    'src/jvm/io/fsq/twofishes/util',
    'src/thrift/io/fsq/twofishes',
  ],
)
