# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:mongodb',
    'src/jvm/io/fsq/twofishes/util',
    'test/jvm/io/fsq/specs2',
  ],
)
